from app.demo_data import DemoSeedBundle
from app.models.conflict import ConflictRecord
from app.models.grid import Grid
from app.models.house import House, HousingHistory
from app.models.person import Person
from app.models.visit import VisitRecord
from app.demo_data.regions import REGION_GRID_CATALOG


def build_hero_bundle() -> DemoSeedBundle:
    return DemoSeedBundle(
        grids=[
            Grid(id=item.id, name=item.grid_name, managerName=item.manager_name)
            for item in REGION_GRID_CATALOG
        ],
        houses=[
            House(
                id="h_hero_001",
                gridId="g1",
                address="海梦苑9号楼1单元101",
                communityName="海梦苑",
                building="9号楼",
                unit="1单元",
                room="101",
                ownerName="周秀兰",
                area="78㎡",
                type="自住",
                memberCount=1,
                tags=["独居老人", "慢病管理", "重点回访"],
                updatedAt="2026-04-14",
                houseType="普通住宅",
                ownerPhone="13800010001",
                ownerAddress="海梦苑9号楼1单元101",
                occupancyStatus="人在户在",
                residenceType="自住",
            ),
            House(
                id="h_hero_002",
                gridId="g1",
                address="海梦苑9号楼3单元301",
                communityName="海梦苑",
                building="9号楼",
                unit="3单元",
                room="301",
                ownerName="赵建国",
                area="108㎡",
                type="出租",
                memberCount=5,
                tags=["群租风险", "流动人口", "夜间扰民"],
                updatedAt="2026-04-15",
                houseType="普通住宅",
                ownerPhone="13800010002",
                ownerAddress="烟台市蓬莱区文化西路88号",
                occupancyStatus="户在人不在",
                residenceType="租住",
            ),
            House(
                id="h_hero_003",
                gridId="g2",
                address="海梦苑3号楼2单元402",
                communityName="海梦苑",
                building="3号楼",
                unit="2单元",
                room="402",
                ownerName="冯建国",
                area="96㎡",
                type="自住",
                memberCount=1,
                tags=["重点关注", "长期未走访"],
                updatedAt="2026-04-12",
                houseType="普通住宅",
                ownerPhone="13800010003",
                ownerAddress="海梦苑3号楼2单元402",
                occupancyStatus="人在户在",
                residenceType="自住",
            ),
            House(
                id="h_hero_004",
                gridId="g2",
                address="海梦苑6号楼1单元201",
                communityName="海梦苑",
                building="6号楼",
                unit="1单元",
                room="201",
                ownerName="吴守礼",
                area="88㎡",
                type="自住",
                memberCount=1,
                tags=["赡养纠纷", "高龄老人"],
                updatedAt="2026-04-14",
                houseType="普通住宅",
                ownerPhone="13800010004",
                ownerAddress="海梦苑6号楼1单元201",
                occupancyStatus="人在户在",
                residenceType="自住",
            ),
            House(
                id="h_hero_005",
                gridId="g2",
                address="海梦苑12号楼2单元502",
                communityName="海梦苑",
                building="12号楼",
                unit="2单元",
                room="502",
                ownerName="秦志远",
                area="118㎡",
                type="自住",
                memberCount=2,
                tags=["邻里纠纷关联户"],
                updatedAt="2026-04-15",
                houseType="普通住宅",
                ownerPhone="13800010005",
                ownerAddress="海梦苑12号楼2单元502",
                occupancyStatus="人在户在",
                residenceType="自住",
            ),
            House(
                id="h_hero_006",
                gridId="g2",
                address="海梦苑12号楼2单元602",
                communityName="海梦苑",
                building="12号楼",
                unit="2单元",
                room="602",
                ownerName="许静",
                area="118㎡",
                type="自住",
                memberCount=2,
                tags=["邻里纠纷关联户", "夜间装修"],
                updatedAt="2026-04-15",
                houseType="普通住宅",
                ownerPhone="13800010006",
                ownerAddress="海梦苑12号楼2单元602",
                occupancyStatus="人在户在",
                residenceType="自住",
            ),
            House(
                id="h_hero_007",
                gridId="g2",
                address="海梦苑2号楼1单元102",
                communityName="海梦苑",
                building="2号楼",
                unit="1单元",
                room="102",
                ownerName="陈晓梅",
                area="82㎡",
                type="自住",
                memberCount=3,
                tags=["低保家庭", "困境帮扶"],
                updatedAt="2026-04-13",
                houseType="普通住宅",
                ownerPhone="13800010007",
                ownerAddress="海梦苑2号楼1单元102",
                occupancyStatus="人在户在",
                residenceType="自住",
            ),
            House(
                id="h_hero_008",
                gridId="g1",
                address="海梦苑10号楼1单元401",
                communityName="海梦苑",
                building="10号楼",
                unit="1单元",
                room="401",
                ownerName="韩振国",
                area="104㎡",
                type="自住",
                memberCount=2,
                tags=["退役军人", "志愿骨干"],
                updatedAt="2026-04-15",
                houseType="普通住宅",
                ownerPhone="13800010008",
                ownerAddress="海梦苑10号楼1单元401",
                occupancyStatus="人在户在",
                residenceType="自住",
            ),
        ],
        housing_histories=[
            HousingHistory(
                id="hh_hero_001",
                houseId="h_hero_001",
                personName="周建国",
                type="家属",
                period="1989-05 ~ 2023-11",
                moveOutReason="配偶去世，房屋现由周秀兰独居。",
            ),
            HousingHistory(
                id="hh_hero_002",
                houseId="h_hero_002",
                personName="宋鹏",
                type="租客",
                period="2025-02 ~ 2025-11",
                moveOutReason="租约到期后退租，之后房屋改为多人合租。",
            ),
            HousingHistory(
                id="hh_hero_003",
                houseId="h_hero_004",
                personName="吴建平",
                type="家属",
                period="2019-03 ~ 2024-08",
                moveOutReason="长期外地务工，仅节假日返家探望父亲。",
            ),
            HousingHistory(
                id="hh_hero_004",
                houseId="h_hero_007",
                personName="陈晓梅",
                type="业主",
                period="2021-05 ~ 至今",
                moveOutReason=None,
            ),
            HousingHistory(
                id="hh_hero_005",
                houseId="h_hero_008",
                personName="韩振国",
                type="业主",
                period="2017-10 ~ 至今",
                moveOutReason=None,
            ),
        ],
        people=[
            Person(
                id="p_hero_001",
                gridId="g1",
                houseId="h_hero_001",
                name="周秀兰",
                idCard="310115194703120021",
                gender="女",
                age=79,
                phone="13800020001",
                address="海梦苑9号楼1单元101",
                type="户籍",
                tags=["独居老人", "慢病管理", "重点回访"],
                risk="High",
                updatedAt="2026-04-14",
                nation="汉族",
                education="初中",
                maritalStatus="丧偶",
                careLabels=["独居老人", "低保户"],
                biography="退休纺织工人，子女在外地工作，近两年主要依靠社区和邻里照看。",
                healthRecord={
                    "hasChronic": True,
                    "chronicDetails": "高血压、糖尿病",
                    "needsRegularMedicine": True,
                    "medicineFrequency": "每月一次",
                    "medicalVisitFrequency": "每季度一次",
                    "isSeverePatient": False,
                    "isPregnant": False,
                    "specialNotes": "腿脚不便，需要上门随访提醒复诊。",
                },
                activityParticipation={
                    "activities": "偶尔参加社区老年课堂。",
                    "needs": "需要协助购药、复诊陪同和应急联系人回访。",
                },
                importantEvents="2026-03-03 因血压波动由网格员陪同前往社区卫生站复查。",
            ),
            Person(
                id="p_hero_010",
                gridId="g1",
                houseId="h_hero_002",
                name="赵建国",
                idCard="310115198903080035",
                gender="男",
                age=37,
                phone="13800020010",
                address="海梦苑9号楼3单元301",
                type="流动",
                tags=["群租风险", "出租房承租人"],
                risk="High",
                updatedAt="2026-04-15",
                education="高中",
                workplace="冷链仓储夜班主管",
            ),
            Person(
                id="p_hero_011",
                gridId="g1",
                houseId="h_hero_002",
                name="郭海涛",
                idCard="310115199209050019",
                gender="男",
                age=34,
                phone="13800020011",
                address="海梦苑9号楼3单元301",
                type="流动",
                tags=["流动人口", "夜班务工"],
                risk="Medium",
                updatedAt="2026-04-15",
                education="中专",
            ),
            Person(
                id="p_hero_012",
                gridId="g1",
                houseId="h_hero_002",
                name="梁晓静",
                idCard="310115199508210028",
                gender="女",
                age=30,
                phone="13800020012",
                address="海梦苑9号楼3单元301",
                type="流动",
                tags=["流动人口", "多点就业"],
                risk="Medium",
                updatedAt="2026-04-15",
                education="大专",
            ),
            Person(
                id="p_hero_013",
                gridId="g1",
                houseId="h_hero_002",
                name="孙立峰",
                idCard="310115199611040017",
                gender="男",
                age=29,
                phone="13800020013",
                address="海梦苑9号楼3单元301",
                type="流动",
                tags=["流动人口", "合租"],
                risk="Medium",
                updatedAt="2026-04-15",
                education="高中",
            ),
            Person(
                id="p_hero_014",
                gridId="g1",
                houseId="h_hero_002",
                name="白雪",
                idCard="310115199812260024",
                gender="女",
                age=27,
                phone="13800020014",
                address="海梦苑9号楼3单元301",
                type="流动",
                tags=["流动人口", "群租风险"],
                risk="Medium",
                updatedAt="2026-04-15",
                education="本科",
            ),
            Person(
                id="p_hero_020",
                gridId="g2",
                houseId="h_hero_003",
                name="冯建国",
                idCard="310115198001090018",
                gender="男",
                age=46,
                phone="13800020020",
                address="海梦苑3号楼2单元402",
                type="户籍",
                tags=["重点关注", "长期未走访"],
                risk="High",
                updatedAt="2026-04-12",
                education="高中",
                categoryLabels={"focusType": ["社区矫正"]},
                importantEvents="2026-02-18 后无新的走访记录，当前处于超期未回访状态。",
            ),
            Person(
                id="p_hero_030",
                gridId="g2",
                houseId="h_hero_004",
                name="吴守礼",
                idCard="310115195011280019",
                gender="男",
                age=75,
                phone="13800020030",
                address="海梦苑6号楼1单元201",
                type="户籍",
                tags=["高龄老人", "赡养纠纷"],
                risk="High",
                updatedAt="2026-04-14",
                education="小学",
                maritalStatus="丧偶",
                familyRelations=[
                    {"relatedPersonId": "p_hero_031", "relationType": "子女"},
                    {"relatedPersonId": "p_hero_032", "relationType": "子女"},
                ],
                careLabels=["独居老人"],
                healthRecord={
                    "hasChronic": True,
                    "chronicDetails": "心脏病、腿部旧伤",
                    "needsRegularMedicine": True,
                    "medicineFrequency": "每月一次",
                    "medicalVisitFrequency": "每两个月一次",
                    "isSeverePatient": False,
                    "isPregnant": False,
                },
            ),
            Person(
                id="p_hero_031",
                gridId="g2",
                houseId=None,
                name="吴建平",
                idCard="310115198212170012",
                gender="男",
                age=43,
                phone="13800020031",
                address="烟台市蓬莱区海滨路16号",
                type="户籍",
                tags=["赡养纠纷关联人"],
                risk="Medium",
                updatedAt="2026-04-14",
                familyRelations=[{"relatedPersonId": "p_hero_030", "relationType": "父亲"}],
            ),
            Person(
                id="p_hero_032",
                gridId="g2",
                houseId=None,
                name="吴桂兰",
                idCard="310115198611090025",
                gender="女",
                age=40,
                phone="13800020032",
                address="蓬莱区云栖路22号",
                type="户籍",
                tags=["赡养纠纷关联人"],
                risk="Medium",
                updatedAt="2026-04-14",
                familyRelations=[{"relatedPersonId": "p_hero_030", "relationType": "父亲"}],
            ),
            Person(
                id="p_hero_040",
                gridId="g2",
                houseId="h_hero_005",
                name="秦志远",
                idCard="310115198705180031",
                gender="男",
                age=38,
                phone="13800020040",
                address="海梦苑12号楼2单元502",
                type="户籍",
                tags=["邻里纠纷关联人"],
                risk="Medium",
                updatedAt="2026-04-15",
            ),
            Person(
                id="p_hero_041",
                gridId="g2",
                houseId="h_hero_005",
                name="林晓芸",
                idCard="310115198903090026",
                gender="女",
                age=37,
                phone="13800020041",
                address="海梦苑12号楼2单元502",
                type="户籍",
                tags=["邻里纠纷关联人"],
                risk="Low",
                updatedAt="2026-04-15",
                familyRelations=[{"relatedPersonId": "p_hero_040", "relationType": "配偶"}],
            ),
            Person(
                id="p_hero_042",
                gridId="g2",
                houseId="h_hero_006",
                name="许静",
                idCard="310115198412030023",
                gender="女",
                age=41,
                phone="13800020042",
                address="海梦苑12号楼2单元602",
                type="户籍",
                tags=["邻里纠纷关联人", "夜间装修"],
                risk="Medium",
                updatedAt="2026-04-15",
            ),
            Person(
                id="p_hero_043",
                gridId="g2",
                houseId="h_hero_006",
                name="许泽民",
                idCard="310115198306250011",
                gender="男",
                age=42,
                phone="13800020043",
                address="海梦苑12号楼2单元602",
                type="户籍",
                tags=["邻里纠纷关联人"],
                risk="Low",
                updatedAt="2026-04-15",
                familyRelations=[{"relatedPersonId": "p_hero_042", "relationType": "配偶"}],
            ),
            Person(
                id="p_hero_050",
                gridId="g2",
                houseId="h_hero_007",
                name="陈晓梅",
                idCard="310115198908140028",
                gender="女",
                age=36,
                phone="13800020050",
                address="海梦苑2号楼1单元102",
                type="户籍",
                tags=["低保家庭", "困境帮扶"],
                risk="Medium",
                updatedAt="2026-04-13",
                education="中专",
                careLabels=["困难"],
                familyRelations=[
                    {"relatedPersonId": "p_hero_051", "relationType": "子女"},
                    {"relatedPersonId": "p_hero_052", "relationType": "母亲"},
                ],
                activityParticipation={"needs": "希望获得就业推荐和暑期托管支持。"},
            ),
            Person(
                id="p_hero_051",
                gridId="g2",
                houseId="h_hero_007",
                name="陈可欣",
                idCard="310115201409200028",
                gender="女",
                age=11,
                phone=None,
                address="海梦苑2号楼1单元102",
                type="户籍",
                tags=["困境儿童"],
                risk="Medium",
                updatedAt="2026-04-13",
                education="小学",
                familyRelations=[{"relatedPersonId": "p_hero_050", "relationType": "母亲"}],
            ),
            Person(
                id="p_hero_052",
                gridId="g2",
                houseId="h_hero_007",
                name="李玉华",
                idCard="310115196506100029",
                gender="女",
                age=60,
                phone="13800020052",
                address="海梦苑2号楼1单元102",
                type="户籍",
                tags=["困难家庭成员"],
                risk="Low",
                updatedAt="2026-04-13",
                careLabels=["困难"],
                familyRelations=[{"relatedPersonId": "p_hero_050", "relationType": "子女"}],
            ),
            Person(
                id="p_hero_060",
                gridId="g1",
                houseId="h_hero_008",
                name="韩振国",
                idCard="310115198104010033",
                gender="男",
                age=45,
                phone="13800020060",
                address="海梦苑10号楼1单元401",
                type="户籍",
                tags=["退役军人", "志愿骨干", "低风险样板"],
                risk="Low",
                updatedAt="2026-04-15",
                education="大专",
                militaryService=True,
                communityVolunteer=True,
                skills="应急救援、楼栋协调、退役军人志愿服务",
                categoryLabels={"isUnitLeader": True},
                activityParticipation={
                    "activities": "参与夜巡、消防演练和新就业群体联络。",
                    "needs": "希望增加退役军人志愿积分激励。",
                },
            ),
            Person(
                id="p_hero_061",
                gridId="g1",
                houseId="h_hero_008",
                name="姜敏",
                idCard="310115198304180024",
                gender="女",
                age=43,
                phone="13800020061",
                address="海梦苑10号楼1单元401",
                type="户籍",
                tags=["志愿骨干家庭"],
                risk="Low",
                updatedAt="2026-04-15",
                familyRelations=[{"relatedPersonId": "p_hero_060", "relationType": "配偶"}],
            ),
        ],
        visits=[
            VisitRecord(
                id="v_hero_001",
                targetId="p_hero_001",
                targetType="person",
                gridId="g1",
                visitorName="李明辉",
                date="2026-03-10",
                content="例行探访独居老人，核对血压、用药和紧急联系人情况。",
                images=[],
                tags=["独居老人", "慢病管理"],
            ),
            VisitRecord(
                id="v_hero_002",
                targetId="p_hero_001",
                targetType="person",
                gridId="g1",
                visitorName="李明辉",
                date="2026-04-12",
                content="陪同完成复诊预约，提醒近期天气变化和复诊安排，补录药品余量。",
                images=[],
                tags=["重点回访", "社工助手"],
            ),
            VisitRecord(
                id="v_hero_003",
                targetId="h_hero_002",
                targetType="house",
                gridId="g1",
                visitorName="李明辉",
                date="2026-04-11",
                content="夜间核查 9 号楼群租房，确认实际居住 5 人，存在电瓶入户充电和楼道杂物堆放。",
                images=[],
                tags=["群租风险", "房屋核查"],
            ),
            VisitRecord(
                id="v_hero_004",
                targetId="p_hero_010",
                targetType="person",
                gridId="g1",
                visitorName="李明辉",
                date="2026-04-13",
                content="约谈主承租人，要求限期整改居住人数、配合登记流动人口信息。",
                images=[],
                tags=["流动人口", "整改约谈"],
            ),
            VisitRecord(
                id="v_hero_005",
                targetId="p_hero_020",
                targetType="person",
                gridId="g2",
                visitorName="王海燕",
                date="2026-02-18",
                content="节前了解近况，提醒遵守社区矫正外出报备要求。",
                images=[],
                tags=["重点关注"],
            ),
            VisitRecord(
                id="v_hero_006",
                targetId="p_hero_030",
                targetType="person",
                gridId="g2",
                visitorName="王海燕",
                date="2026-04-09",
                content="上门了解老人赡养诉求，确认近期子女探望频次较低，老人情绪波动明显。",
                images=[],
                tags=["赡养纠纷", "家庭调解"],
            ),
            VisitRecord(
                id="v_hero_007",
                targetId="p_hero_040",
                targetType="person",
                gridId="g2",
                visitorName="王海燕",
                date="2026-04-08",
                content="核实噪音扰民投诉，收集 502 室当事人的休息受影响时段和诉求。",
                images=[],
                tags=["邻里纠纷", "诉求采集"],
            ),
            VisitRecord(
                id="v_hero_008",
                targetId="p_hero_042",
                targetType="person",
                gridId="g2",
                visitorName="王海燕",
                date="2026-04-09",
                content="提醒装修作业需避开午休时段，并补录施工计划和装修公司联系方式。",
                images=[],
                tags=["邻里纠纷", "整改提醒"],
            ),
            VisitRecord(
                id="v_hero_009",
                targetId="p_hero_050",
                targetType="person",
                gridId="g2",
                visitorName="王海燕",
                date="2026-04-06",
                content="核实低保家庭近期收入和子女就学情况，记录就业与托管需求。",
                images=[],
                tags=["困难帮扶", "家庭需求"],
            ),
            VisitRecord(
                id="v_hero_010",
                targetId="p_hero_060",
                targetType="person",
                gridId="g1",
                visitorName="李明辉",
                date="2026-04-14",
                content="邀请参与小区消防演练志愿队，确认可承担单元联络工作。",
                images=[],
                tags=["志愿骨干", "正向案例"],
            ),
        ],
        conflicts=[
            ConflictRecord(
                id="c_hero_001",
                source="上级下派",
                title="海梦苑 9 号楼群租扰民投诉",
                type="物业纠纷",
                description="物业和周边住户反映 9 号楼 3 单元 301 房存在群租、电瓶入户充电和夜间出入频繁问题，需要核查并协调整改。",
                involvedParties=[
                    {"type": "resident", "id": "p_hero_010", "name": "赵建国"},
                    {"type": "organization", "id": "PROPERTY_MGMT", "name": "海梦苑物业"},
                ],
                status="调解中",
                gridId="g1",
                location="海梦苑9号楼3单元301",
                timeline=[
                    {"date": "2026-04-10 20:30", "content": "物业上报群租线索。", "operator": "系统管理员"},
                    {"date": "2026-04-11 21:00", "content": "网格员夜查确认 5 人同住。", "operator": "李明辉"},
                ],
                images=[],
                createdAt="2026-04-10 20:30:00",
                updatedAt="2026-04-11 21:00:00",
            ),
            ConflictRecord(
                id="c_hero_002",
                source="上级下派",
                title="海梦苑老人赡养纠纷",
                type="家庭纠纷",
                description="独居老人反映子女探望频次和赡养支出无法达成一致，需要社区牵头调解并形成后续回访计划。",
                involvedParties=[
                    {"type": "resident", "id": "p_hero_030", "name": "吴守礼"},
                    {"type": "resident", "id": "p_hero_031", "name": "吴建平"},
                    {"type": "resident", "id": "p_hero_032", "name": "吴桂兰"},
                ],
                status="调解中",
                gridId="g2",
                location="海梦苑6号楼1单元201",
                timeline=[
                    {"date": "2026-04-08 09:30", "content": "民政条线转来老人求助。", "operator": "系统管理员"},
                    {"date": "2026-04-09 14:00", "content": "首次入户走访，确认老人诉求。", "operator": "王海燕"},
                ],
                images=[],
                createdAt="2026-04-08 09:30:00",
                updatedAt="2026-04-09 14:00:00",
            ),
            ConflictRecord(
                id="c_hero_003",
                source="上级下派",
                title="海梦苑 12 号楼午休时段装修噪音",
                type="邻里纠纷",
                description="12 号楼 2 单元 602 在午休时段持续施工，502 室住户投诉休息受到影响，需要协调装修时间与后续回访。",
                involvedParties=[
                    {"type": "resident", "id": "p_hero_040", "name": "秦志远"},
                    {"type": "resident", "id": "p_hero_042", "name": "许静"},
                ],
                status="调解中",
                gridId="g2",
                location="海梦苑12号楼2单元",
                timeline=[
                    {"date": "2026-04-08 11:00", "content": "12345 热线转派噪音投诉。", "operator": "系统管理员"},
                    {"date": "2026-04-09 10:30", "content": "走访双方并确认装修作业时段。", "operator": "王海燕"},
                ],
                images=[],
                createdAt="2026-04-08 11:00:00",
                updatedAt="2026-04-09 10:30:00",
            ),
        ],
    )
