#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
TARGET_ROOT="${1:-/Users/rayli/Desktop/homedata-web}"
PROJECTION_REPO="${PROJECTION_REPO:-MochenRay/homedata-web}"
BASE_BRANCH="${BASE_BRANCH:-main}"

if ! command -v gh >/dev/null 2>&1; then
  echo "ERROR: gh CLI is required." >&2
  exit 2
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "ERROR: gh CLI is not authenticated." >&2
  exit 2
fi

if ! git -C "${TARGET_ROOT}" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "ERROR: target is not a git repository: ${TARGET_ROOT}" >&2
  exit 2
fi

if [[ -n "$(git -C "${SOURCE_ROOT}" status --porcelain)" && "${ALLOW_DIRTY_SOURCE:-0}" != "1" ]]; then
  echo "ERROR: source repo has uncommitted changes; commit first or set ALLOW_DIRTY_SOURCE=1." >&2
  git -C "${SOURCE_ROOT}" status --short >&2
  exit 2
fi

if [[ -n "$(git -C "${TARGET_ROOT}" status --porcelain)" ]]; then
  echo "ERROR: target repo has uncommitted changes; commit or clean them first." >&2
  git -C "${TARGET_ROOT}" status --short >&2
  exit 2
fi

SOURCE_SHA="$(git -C "${SOURCE_ROOT}" rev-parse HEAD)"
SOURCE_SHORT_SHA="$(git -C "${SOURCE_ROOT}" rev-parse --short HEAD)"
SYNC_BRANCH="sync/source-${SOURCE_SHORT_SHA}"

git -C "${TARGET_ROOT}" fetch origin "${BASE_BRANCH}" >/dev/null
git -C "${TARGET_ROOT}" checkout -B "${SYNC_BRANCH}" "origin/${BASE_BRANCH}" >/dev/null

"${SCRIPT_DIR}/sync_homedata_web.sh" "${TARGET_ROOT}"

if [[ -z "$(git -C "${TARGET_ROOT}" status --porcelain)" ]]; then
  echo "OK: no projection changes for ${SOURCE_SHA}"
  exit 0
fi

git -C "${TARGET_ROOT}" add -A
git -C "${TARGET_ROOT}" commit -m "sync: source ${SOURCE_SHORT_SHA}"
git -C "${TARGET_ROOT}" push -u origin "${SYNC_BRANCH}"

EXISTING_PR_URL="$(gh pr list -R "${PROJECTION_REPO}" --head "${SYNC_BRANCH}" --state open --json url --jq '.[0].url // ""')"
if [[ -n "${EXISTING_PR_URL}" ]]; then
  echo "PR already exists: ${EXISTING_PR_URL}"
  exit 0
fi

gh pr create \
  -R "${PROJECTION_REPO}" \
  --base "${BASE_BRANCH}" \
  --head "${SYNC_BRANCH}" \
  --title "sync: source ${SOURCE_SHORT_SHA}" \
  --body "Generated by \`scripts/sync_homedata_web_pr.sh\` from source commit \`${SOURCE_SHA}\`."
